AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to deploy lambda function
Parameters:
  project:
    Type: String
    Default: leadhawk
    Description:  Project Name
  env:
    Type: String
    Default: dev
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description:  Application Name
  s3ArtifactPath:
    Type: String
    Default: "https://leadhawk-app-dev-us-east-1-627414718330.s3.amazonaws.com/code/cfn/services"
    Description: Artifact Bucket Path
Resources:
  restrictDefaultSgLambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambdaFunction/lambdaFunction-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        app: restrictDefaultSg
        lambdaPackageType: Zip
        deployInVPC: True
        privateSubnet01: !Select [2, !Split [",", !GetAtt vpc.Outputs.SubnetIds]]
        privateSubnet02: !Select [3, !Split [",", !GetAtt vpc.Outputs.SubnetIds]]
        s3BucketName: !Sub "${project}-${app}-${env}-${AWS::Region}-${AWS::AccountId}"
        s3ObjectKey: restrictDefaultSg/ee7de53d64cc9d6248fa6aa550f92358f6c907b5efd6f3298aeab1b5e7ea358a.zip
        ecrRepositoryUri: ""
        ecrImageTag: ""
Outputs:
  lambdaFunction:
    Value: !Ref lambdaFunction
    Export:
      Name: !Sub "${project}-${env}-${app}-lambdaFunction-${AWS::Region}"