AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template to deploy IAM user
Parameters:
  project:
    Type: String
    Default: leadhawk
    Description: Project Name
  env:
    Type: String
    Default: dev
    AllowedValues: [prod, dev, qa, stage]
    Description: Environment Name
  app:
    Type: String
    Default: app
    Description: Application Name
  createAccessKey:
    Type: String
    Default: yes
    AllowedValues: [yes, no]
    Description: Create Access Key or not
Conditions:
  isCreateAccessKey: !Equals [!Ref createAccessKey, yes ]
Resources:
  iamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${project}-${env}-${app}-iamUser"
      Tags:
        - Key: Name
          Value: !Sub "${project}-${env}-${app}-iamUser"
        - Key: project
          Value: !Ref project
        - Key: environment
          Value: !Ref env
        - Key: app
          Value: !Ref app
  iamUserAccessKey:
    Type: AWS::IAM::AccessKey
    Condition: isCreateAccessKey
    Properties:
      UserName: !Ref iamUser
Outputs:
  iamUserName:
    Description: Name of an IAM user
    Value: !Ref iamUser
    Export:
      Name: !Sub "${project}-${env}-${app}-iamUser-${AWS::Region}"
  iamUserAccessKeyId:
    Description: IAM user access key
    Value: !Ref iamUserAccessKey
    Export:
      Name: !Sub "${project}-${env}-${app}-iamUserAccessKeyId-${AWS::Region}"
  iamUserSecretAccessKey:
    Description: IAM user secret access key
    Value: !GetAtt iamUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub "${project}-${env}-${app}-iamUserSecretAccessKey-${AWS::Region}"