AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to deploy ECR
Parameters:
  project:
    Type: String
    Default: bottest-ai
    Description:  Project Name
  env:
    Type: String
    Default: prod
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description:  Application Name
  s3ArtifactPath:
    Type: String
    Default: "https://bottest-ai-app-prod-us-east-1-122253718099.s3.amazonaws.com/code/cfn/services"
    Description: Artifact Bucket Path
Resources:
  ecrRepository:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/ecr/ecr-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        app: !Ref app
        purgeRepo: True
Outputs:
  ecrRepository:
    Value: !Ref ecrRepository
    Export:
      Name: !Sub "${project}-${env}-${app}-ecrRepository-${AWS::Region}"