AWSTemplateFormatVersion: "2010-09-09"
Description: 'CloudFormation Template to deploy Cloudwatch Event rules'
Parameters:
  project:
    Type: String
    Default: leadhawk
    Description: Project Name
  env:
    Type: String
    Default: dev
    AllowedValues: [prod, dev, qa, stage]
    Description: Environment Name
  app:
    Type: String
    Default: app
    Description: Application Name
  schedulerLambdaFunctionArn:
    Type: String
    Description: ARN of scheduler lambda function
Resources:
  oneDayTrialLambdaCwRule:
    Type: AWS::Events::Rule
    Properties:
      Description: CloudWatch event rule to trigger lambda function
      Name: !Sub "${project}-${env}-one-day-remain-trial-cwEventRule"
      ScheduleExpression: cron(0 */1 ? * * *)
      State: ENABLED
      Targets:
        - Id: schedulerLambdaFunction
          Arn: !Ref schedulerLambdaFunctionArn
  oneDayTrialLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref schedulerLambdaFunctionArn
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt oneDayTrialLambdaCwRule.Arn
  expiredTrialLambdaCwRule:
    Type: AWS::Events::Rule
    Properties:
      Description: CloudWatch event rule to trigger lambda function
      Name: !Sub "${project}-${env}-trial-expired-cwEventRule"
      ScheduleExpression: cron(15 */1 ? * * *)
      State: ENABLED
      Targets:
        - Id: schedulerLambdaFunction
          Arn: !Ref schedulerLambdaFunctionArn
  expiredTrialLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref schedulerLambdaFunctionArn
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt expiredTrialLambdaCwRule.Arn
Outputs:
  oneDayTrialLambdaCwRuleId:
    Description: One day trial cloudwatch rule Id
    Value: !Ref oneDayTrialLambdaCwRule
    Export:
      Name: !Sub "${project}-${env}-${app}-oneDayTrialLambdaCwRuleId-${AWS::Region}"
  expiredTrialLambdaCwRuleId:
    Description: expired trial cloudwatch rule Id
    Value: !Ref expiredTrialLambdaCwRule
    Export:
      Name: !Sub "${project}-${env}-${app}-expiredTrialLambdaCwRuleId-${AWS::Region}"