Description: Driver Template to deploy Cloudwatch Event rules
Parameters:
  project:
    Type: String
    Default: leadhawk
    Description: Project Name
  env:
    Type: String
    Default: dev
    AllowedValues: [prod, dev, qa, stage]
    Description: Environment Name
  app:
    Type: String
    Default: app
    Description: Application Name
  schedulerLambdaFunctionArn:
    Type: String
    Description: ARN of scheduler lambda function
Resources:
  cwEventRules:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/cw/events/eventRule-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        app: !Ref app
        schedulerLambdaFunctionArn: !GetAtt schedulerLambdaFunction.Outputs.lambdaFunctionArn
Outputs:
  cwEventRules:
    Value: !Ref cwEventRules
    Export:
      Name: !Sub "${project}-${env}-${app}-cwEventRules-${AWS::Region}"